version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    
  db:
    image: postgres:13
    environment: 
      POSTGRES_DB: omerta
      POSTGRES_USER: omerta
      POSTGRES_PASSWORD: omerta
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A omerta worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
  
  celery-beat: 
    build: .
    command: celery -A omerta beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data: